server:
  port: 9020

spring:
  jackson:
    serialization:
      indent_output: true

kafka:
  bootstrap-servers: localhost:9092
  group-id: personal-data-management
  topics:
    command:
      register-person: open-training-offer-acceptance-register-person-command-topic
    event:
      already-registered-person: open-training-offer-acceptance-already-registered-person-event-topic
      person-registered: open-training-offer-acceptance-person-registered-event-topic
