version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka
    entrypoint: >
      sh -c "
      # Wait for Kafka to be ready
      cub kafka-ready -b kafka:9092 1 20 &&
      # Create topics
      kafka-topics --create --topic open-training-offer-acceptance-register-person-command-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-already-registered-person-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-person-registered-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-use-discount-code-command-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-discount-code-used-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-discount-code-already-used-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&or 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-return-discount-code-command-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic open-training-offer-acceptance-discount-code-returned-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-training-offer-published-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-training-offer-rescheduled-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-confirm-training-price-command-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-training-price-changed-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-training-price-not-changed-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-book-training-place-command-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-training-place-booked-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-offer-no-available-training-places-left-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-fact
      kafka-topics --create --topic training-programs-training-program-released-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic training-programs-training-program-rejected-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic reviews-register-proposal-command-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic reviews-proposal-approved-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic reviews-proposal-rejected-event-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
      "
volumes:
  kafka-data:
