server:
  port: 9040

spring:
  jackson:
    serialization:
      indent_output: true

scheduled:
  outbox:
    message:
      rate: 1000

kafka:
  bootstrap-servers: localhost:9092
  group-id: training-offer
  topics:
    trainingoffer:
      commands:
        confirm-training-price: training-offer-confirm-training-price-command-topic
        book-training-place: training-offer-book-training-place-command-topic
      events:
        training-offer-published: training-offer-training-offer-published-event-topic
        training-price-changed: training-offer-training-price-changed-event-topic
        training-price-not-changed: training-offer-training-price-not-changed-event-topic
        training-place-booked: training-offer-training-place-booked-event-topic
        no-available-training-places-left: training-offer-no-available-training-places-left-event-topic
