server:
  port: 9040

spring:
  jackson:
    serialization:
      indent_output: true

kafka:
  bootstrap-servers: localhost:9092
  group-id: training-offer
  topics:
    command:
      confirm-training-price: open-training-offer-acceptance-confirm-training-price-command-topic
      book-training-place: open-training-offer-acceptance-book-training-place-command-topic
    event:
      training-price-changed: open-training-offer-acceptance-training-price-changed-event-topic
      training-price-not-changed: open-training-offer-acceptance-training-price-not-changed-event-topic
      training-place-booked: open-training-offer-acceptance-training-place-booked-event-topic
      no-available-training-places-left: open-training-offer-acceptance-no-available-training-places-left-event-topic
