server:
  port: 9060

spring:
  jackson:
    serialization:
      indent_output: true

kafka:
  bootstrap-servers: localhost:9092
  group-id: reviews
  topics:
    reviews:
      events:
        proposal-approved: reviews-proposal-approved-event-topic
    trainingprogram:
      events:
        training-program-proposed: training-programs-training-program-proposed-event-topic