server:
  port: 9060

spring:
  jackson:
    serialization:
      indent_output: true

services:
  trainers-catalogue:
    url: http://localhost:9080

scheduled:
  proposal:
    assignment:
      rate: 60000

kafka:
  bootstrap-servers: localhost:9092
  group-id: reviews
  topics:
    reviews:
      events:
        proposal-approved: reviews-proposal-approved-event-topic
        proposal-assigned: reviews-proposal-assigned-event-topic
        proposal-rejected: reviews-proposal-rejected-event-topic
      commands:
        register-proposal: reviews-register-proposal-command-topic
