server:
  port: 9060

spring:
  jackson:
    serialization:
      indent_output: true

scheduled:
  proposal:
    assignment:
      rate: 3600000  # 1 hour in milliseconds

kafka:
  bootstrap-servers: localhost:9092
  group-id: reviews
  topics:
    reviews:
      events:
        proposal-approved: reviews-proposal-approved-event-topic
        proposal-rejected: reviews-proposal-rejected-event-topic
      commands:
        register-proposal: reviews-register-proposal-command-topic
