server:
  port: 9001

spring:
  jackson:
    serialization:
      indent_output: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  payment-gateway:
    url: http://localhost:9010

scheduled:
  outbox:
    message:
      rate: 100
  order:
    termination:
      rate: 60000
  offer:
    termination:
      rate: 60000

kafka:
  bootstrap-servers: localhost:9092
  topics:
    order:
      pivotal:
        training-purchased: open-training-training-purchased-topic
        order-rejected: open-training-order-rejected-topic
