server:
  port: 9001

spring:
  jackson:
    serialization:
      indent_output: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  payment-gateway:
    url: http://localhost:9010

scheduled:
  outbox:
    message:
      rate: 1000
  order:
    termination:
      rate: 60000
  offer:
    termination:
      rate: 60000

kafka:
  bootstrap-servers: localhost:9092
  group-id: open-training
  topics:
    offer-acceptance:
      commands:
        register-person: open-training-offer-acceptance-register-person-command-topic
      events:
        person-registered: open-training-offer-acceptance-person-registered-event-topic
        already-registered-person: open-training-offer-acceptance-already-registered-person-event-topic
    order:
      pivotal:
        training-purchased: open-training-training-purchased-topic
        order-rejected: open-training-order-rejected-topic
        order-terminated: open-training-order-terminated-topic
        order-cancelled: open-training-order-cancelled-topic
