server:
  port: 9001

spring:
  jackson:
    serialization:
      indent_output: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  payment-gateway:
    url: http://localhost:9010