sonar.projectKey=smalaca-github_training-center-microservices-trainings-catalogue
sonar.organization=smalaca-github
sonar.projectName=Training Center: Trainings Catalogue
sonar.host.url=https://sonarcloud.io
sonar.links.homepage=https://github.com/smalaca/training-center-microservices
sonar.links.issue=https://github.com/smalaca/training-center-microservices/issues

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/jacoco/jacoco-ut/jacoco.xml
sonar.coverage.exclusions=**/TrainingsCatalogueApplication.java
sonar.test.exclusions=**/*Test.java
