name: Training Offer Module

on:
  push:
    branches:
      - master
    paths:
      - 'training-offer/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'training-offer/**'

permissions:
  pull-requests: read

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Test Annotations
        working-directory: ./annotations-test
        run: mvn clean install

      - name: Build Schema Registry
        working-directory: ./schema-registry
        run: mvn clean install

      - name: Tests
        working-directory: ./training-offer
        run: mvn clean verify

      - name: SonarCloud Scan
        working-directory: ./training-offer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=smalaca-github_training-center-microservices-training-offer